### ISSUE TITLE
Color disappears after switching buffers/files

### ISSUE THREAD

**Issue by brockajones** [luochen1990/rainbow#89] opened 2017-10-29 06:43 UTC
After I switch buffers/files and switch back I have to re-enable RainbowToggleOn

**Comment by thobbs** [comment] 2019-04-22 02:25
Adding this to my vimrc fixed the issue for me:
~~~vim
au VimEnter,BufReadPost * :RainbowToggleOn
~~~

**Comment by luochen1990** [comment] 2019-04-25 08:38
Is this still a problem, can we close this now?
What is your operation sequence to reproduce this issue?

**Comment by keyslapper** [comment] 2019-05-09 19:20
I didn't see a solution with thobbs' suggestion.

I also have the following set:
'
let g:rainbow_active = 1
nnoremap <silent> <F9> :RainbowToggle<CR>
`
I've also noticed that even with the rainbow_active setting, color wouldn't work for parentheses until I'd issued the `:RainbowToggle` command (<F9>) twice - once to turn it off, and again to turn it on.

I should note that the solution suggested by thobbs did fix the startup problem, but it still went off when I opened another file or switched buffers.

I did get a better solution with the following adjustment to thobbs' suggestion:
`autocmd BufEnter,BufReadPost * :RainbowToggleOn`

With this, the parens are colored at startup, and when I switch buffers the color is still there.  However, if I'm switching buffers between buffers (different files) in a split screen, the "off" buffer always loses paren coloring.
Also, this is really a "nuclear option" as this setting means I _can't_ turn paren coloring off if one of the buffers doesn't look right with it.

As far as steps to reproduce, I simply open a C file.  Or my .vimrc, or Perl, or any combination of any of the many code files I work with (Bash scripts, Java, endless config files ...).  I tend to use vertically split windows _a lot_, which is where I notice the parens losing color when I switch to another buffer.

I hope this helps you understand what I'm doing wrong.

**Comment by luochen1990** [comment] 2019-05-10 02:44
I'm sorry but I cannot reproduce your problem, Have you updated your plugin to the latest version? and what is your Vim Version?  Could you please provide more information? the following [doc](https://github.com/luochen1990/rainbow/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) can be referenced.

**Comment by luochen1990** [comment] 2019-05-10 02:51
This is what rainbow did:

```
if (exists('g:rainbow_active') && g:rainbow_active)
	auto syntax * call rainbow_main#load()
	auto colorscheme * call rainbow_main#load()
endif
```

**Comment by keyslapper** [comment] 2019-05-10 19:07
I have no doubt the issue is with my config, I'm just trying to understand what I'm doing wrong - thank you for taking the time to help with it.
This is the URL to a small C git repo that I'm seeing this behavior in:
https://github.com/LouLeBlanc/myrand.git

And my exact Vim config can be found here:
https://github.com/keyslapper/config_files
You'll only need the vimrc file and vim directory.  All the plugins I'm using get installed automagically when you open vim for the first time.

Just set up Vim with my config, then navigate into the myrand directory.  Open src/myrand.c and any other file.  You can split the window and switch between buffers to see the .c file lose paren colors.

I did try adding your code snippet to my .vimrc, but I still have to double-toggle with :RainbowToggle (I use <F9>) to get the paren colors, and it still falls off when I switch buffers.

As for other details, I'm using Vim 8.1 on Fedora workstation 29 and 30 installed from the updates repository.

Thank you again
Lou

**Comment by keyslapper** [comment] 2019-05-11 01:06
I believe I may have found the cause of my problem.
A long time ago, I had problems where syntax highlighting would flip off every time I switched buffers (I almost always work with multiple files in vsplit screens).  After much searching, I found a quick hack to flip syntax highlighting "back on" every time I entered a buffer:
autocmd BufEnter * :syntax on

Of course, I didn't realize this was stepping on the rainbow parens plugin, but I did see that adding the following line (after the syntax line above) fixed it:
autocmd BufEnter,BufReadPost * :RainbowToggleOn

Of course, whatever broke syntax highlighting all those years ago has long since been fixed, so now I can remove it.  Then I removed the RainbowToggleOn call just to see what happens, and the rainbow plugin is working as expected.

I took another look through your documentation to see if I missed any mention of "syntax on" but it doesn't appear to be mentioned.  In retrospect, it's perfectly obvious, but perhaps a quick note of the pitfall might be worthwhile?

I don't know if this was thobbs' issue, but as far as I can tell, your plugin works great for me.

Thank you!
Lou

**Comment by luochen1990** [comment] 2019-05-11 11:38
I'm happy to know that you have solved your problem :)   I will close this issue now.

PS:  the `au VimEnter,BufReadPost * :RainbowToggleOn` workaround is not suggestted now, if anybody find rainbow works not as expected, just open a new issue :)

**Closed by luochen1990** 2019-05-11 11:38 UTC
Labels: more description needed
