### ISSUE TITLE
Issues while using plugin with golang

### ISSUE THREAD

**Issue by Gonzih** [luochen1990/rainbow#71] opened 2017-02-23 11:58 UTC
Hi, I tried multiple rainbow plugins so far and ended up using this one since it's one of the most flexible implementations.

I have couple of minor issues with this plugin while using it with golang that I'm not sure how to fix with configuration.

In go struct contractors are often conjoined with type name like so:

![](https://dl.dropboxusercontent.com/u/4109351/tmp/5a13deb8-8e80-4d76-b077-0e31719729b9.png
)

Problem is that opening brace is ignored by rainbow.

Another problem is that method defenition on struct also is getting ignored by plugin (first pair of parentheses):

![](https://dl.dropboxusercontent.com/u/4109351/tmp/25edc993-bd4d-4093-94e8-cfe88adf3793.png
)

I was able to solve first problem by defining diffirent start regexp for braces like `\w*{`. But it then changes color of type name.

Do you have any idea how to solve those issues?

Thanks a lot!

**Comment by luochen1990** [comment] 2017-04-21 10:02
The image is not available now, please upload them again? thx :)

**Comment by Gonzih** [comment] 2017-06-09 13:54
Sorry for the late reply. This is example of how highlighting currently works in golang:

![area-screenshot](https://user-images.githubusercontent.com/266275/26978421-cb94ac32-4d2b-11e7-9001-236a16e80caf.png)

**Comment by luochen1990** [comment] 2018-05-29 12:21
closing since I cannot reproduce this issue.

**Closed by luochen1990** 2018-05-29 12:21 UTC
