### ISSUE TITLE
[Bug] C and C++ syntax breaking on > if () is around it

### ISSUE THREAD

**Issue by TruncatedDinosour** [luochen1990/rainbow#179] opened 2022-04-06 11:13 UTC
### **Describe the bug**
C and C++ syntax breaking on < if () is around it

### **To Reproduce**

1.   Open a C or a C++ file
2.   Write anything that has the syntax of for example `.. (... > ...)`
3.   Profit
 

File: `bug.c`, filetype=c
```c
#include <stdio.h>

int main(int argc, char *argv[]) {
    if (argc < 2) {
        puts("No args ew");
        return 1;
    }

    puts(argv[1]);
    return 0;
}
```

### **Expected behavior**
For it to work

### **Screenshots**
https://imgur.com/a/SeILTUC

### **Additional context**
- https://github.com/vim/vim/issues/10091
- https://github.com/TruncatedDinosour/dotfiles-cleaned/tree/gentoo/dotfiles/editors/vim

**Comment by luochen1990** [comment] 2022-04-07 02:44
This code rendered correctly in my environment.

<img width="223" alt="image" src="https://user-images.githubusercontent.com/2309868/162109779-4972f4f8-ed19-4014-9026-6b1968149c81.png">

Maybe rainbow breaks some other syntax plugin for C.

**Comment by TruncatedDinosour** [comment] 2022-04-07 12:48
- Not CoC
- Not ALE
- Not coffee-theme
- Not vim-surround
- Not `t_Co=256`
- Not indentline
- Not highlightyank
- Not colorizer

No idea what else could it be...
removing rainbow though fixes it:

![mpv-shot0002](https://user-images.githubusercontent.com/71613062/162202334-e31cabe2-981a-4e80-a254-7fe91ce7f0c8.jpg)

**Comment by TruncatedDinosour** [comment] 2022-04-07 12:53
![mpv-shot0001](https://user-images.githubusercontent.com/71613062/162203248-fbff7f2a-8950-4716-812a-6f66c529e379.jpg)
even just  the rainbow plugin does this

**Comment by TruncatedDinosour** [comment] 2022-04-07 12:55
Maybe it's my syntax file by any chance? https://pastebin.com/YdugFeYA

**Comment by TruncatedDinosour** [comment] 2022-04-07 12:58
![mpv-shot0001](https://user-images.githubusercontent.com/71613062/162204029-16cbba6e-e859-41c4-b539-4b0cd9d5d775.jpg)
![mpv-shot0002](https://user-images.githubusercontent.com/71613062/162204101-32ff7d9d-ea1e-46f1-aa6d-6da492592632.jpg)

oddly these examples are fine

**Comment by TruncatedDinosour** [comment] 2022-04-07 13:01
![mpv-shot0003](https://user-images.githubusercontent.com/71613062/162204412-e642576e-f087-4af4-915f-a36796098ee1.jpg)
![mpv-shot0004](https://user-images.githubusercontent.com/71613062/162204488-f3ede297-9f6a-4c97-92f9-2aca1cf785f7.jpg)

I'm pretty sure it's `<` that is causing the issues...

![mpv-shot0001](https://user-images.githubusercontent.com/71613062/162204646-102bc9e7-66a5-474c-bc9f-793375b4a40c.jpg)

It's definally `<`

**Comment by TruncatedDinosour** [comment] 2022-04-09 23:51
@luochen1990 ping

**Comment by luochen1990** [comment] 2022-04-11 11:57
You can disable all other plugins and enable rainbow to check if rainbow works alone.
And to find out which plugin cause this compatibility issue, you can enable them one by one (or bisect) and test the result.

**Comment by TruncatedDinosour** [comment] 2022-04-16 20:21
@luochen1990 ping

**Comment by TruncatedDinosour** [comment] 2022-04-20 12:45
@luochen1990 ping2

**Comment by luochen1990** [comment] 2022-04-21 07:06
Have you read this: https://github.com/luochen1990/rainbow#troubleshooting

Please use the tool to check the syntax name and definitions under the cursor

**Comment by TruncatedDinosour** [comment] 2022-04-21 11:39
> Have you read this: https://github.com/luochen1990/rainbow#troubleshooting
> 
> Please use the tool to check the syntax name and definitions under the cursor

f1: cParenError
f2: hi<cParenError> trans<cParenError> lo<Error>
f3: ['cRainbow_lv0_r3', 'cRainbow_lv1_r1', 'cRainbow_lv2_r0', 'cParenError']
f4:
```vim
--- Syntax items ---
cParenError    xxx match /[\])]/  display
                   links to cError
```

**Comment by TruncatedDinosour** [comment] 2022-04-26 21:45
@luochen1990 ping

**Comment by luochen1990** [comment] 2022-05-13 08:49
The information you provided is not enough to find the issue.  You have to check them before and after the buggy position,  and find out which syntax rule cause the bug yourself ...

**Comment by TruncatedDinosour** [comment] 2022-05-15 19:36
> The information you provided is not enough to find the issue. You have to check them before and after the buggy position, and find out which syntax rule cause the bug yourself ...

I'm confused, what do I do...?

**Comment by luochen1990** [comment] 2022-05-24 02:28
@TruncatedDinosour You can probably not solve this issue if you know little about vim syntax highlighting mechanism, maybe read about `:h syntax-highlighting` will help.

And if your issue is about "how to make `<` inside parentheses highlighted", then [this](https://github.com/luochen1990/rainbow/issues/183) might help you as a configuration reference.

**Comment by TruncatedDinosour** [comment] 2022-05-30 12:50
> @TruncatedDinosour You can probably not solve this issue if you know little about vim syntax highlighting mechanism, maybe read about `:h syntax-highlighting` will help.
> 
> And if your issue is about "how to make `<` inside parentheses highlighted", then [this](https://github.com/luochen1990/rainbow/issues/183) might help you as a configuration reference.

I'm confused sorry

**Comment by luochen1990** [comment] 2022-06-06 06:29
closing it since I cannot reproduce it.   you can reopen it if you find someway to reproduce it on some other environment

**Closed by luochen1990** 2022-06-06 06:29 UTC
Labels: more description needed
